// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "memoapi/model"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// CreateMemo provides a mock function with given fields: ctx, m
func (_m *Usecase) CreateMemo(ctx context.Context, m *model.Memo) error {
	ret := _m.Called(ctx, m)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Memo) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllMemo provides a mock function with given fields: ctx
func (_m *Usecase) GetAllMemo(ctx context.Context) ([]*model.Memo, error) {
	ret := _m.Called(ctx)

	var r0 []*model.Memo
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Memo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Memo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMemoByID provides a mock function with given fields: ctx, id
func (_m *Usecase) GetMemoByID(ctx context.Context, id int) (*model.Memo, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.Memo
	if rf, ok := ret.Get(0).(func(context.Context, int) *model.Memo); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Memo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecase(t mockConstructorTestingTNewUsecase) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
